class Rect:
    _left: int
    _top: int
    _right: int
    _bottom: int
    def __init__(self, left: int, top: int, right: int, bottom: int) -> None: ...

    @property
    def top(self) -> int: ...

    @property
    def left(self) -> int: ...

    @property
    def bottom(self) -> int: ...

    @property
    def right(self) -> int: ...

    def rect(self) -> tuple: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...
