from .core import Pos


def mouse_move_to(pos: Pos, duration: float = 0.0) -> None: ...


def mouse_click_position(pos: Pos, button: str = "left") -> None: ...


def mouse_scroll(scale: int, count: int = 1) -> None: ...


def mouse_drag(start: Pos, end: Pos, button='left') -> None: ...


def mouse_click(button: str) -> None: ...


def keyboard_down(key: str) -> None: ...


def keyboard_up(key: str) -> None: ...


def keyboard_press(key: str) -> None: ...
